"""Datasets generated by querying the physics kernel M.

The dataset carries the scene STATE x alongside the observation. The audited schema dropped
it, which quietly made contribution C2 impossible: J(x) is a derivative with respect to x,
so a pipeline that never materializes x cannot compute the paper's identifiability result no
matter what else it does. Carrying x costs a few floats and buys the headline experiment.

It also carries importance WEIGHTS, so that a boundary-focused action sampler (Section 11,
reviewer attack 27) can be debiased at the loss (V4). The audited loss took a plain mean over
a biased sample, so adding the prescribed sampler would have silently introduced the exact
bias Reviewer B flagged.
"""

from __future__ import annotations

from dataclasses import dataclass

import torch
from torch import Tensor
from torch.utils.data import Dataset

from msp.oracle.synthetic import SyntheticOracle

__all__ = ["SyntheticGraspDataset", "collate"]


@dataclass
class SyntheticGraspDataset(Dataset[dict[str, Tensor]]):
    """Scenes drawn from p(x), observed through p(o|x), with outcomes queried from M.

    Args:
        oracle: the physics kernel.
        n_scenes: |D|.
        n_actions: Na candidate actions evaluated per scene.
        obs_dim: dimensionality of the vector observation.
        boundary_focus: if > 0, a fraction of actions are resampled near the outcome
            decision boundary (where sigma(f) ~ 0.5), which is where the label is
            informative. Importance weights are returned so the loss can correct for it.
        seed: reproducibility.
    """

    oracle: SyntheticOracle
    n_scenes: int = 2048
    n_actions: int = 16
    obs_dim: int = 32
    boundary_focus: float = 0.0
    seed: int = 0

    def __post_init__(self) -> None:
        g = torch.Generator().manual_seed(self.seed)
        self.states = self.oracle.sample_states(self.n_scenes, generator=g)
        self.obs = self.oracle.observe(self.states, obs_dim=self.obs_dim)

        actions = torch.randn(self.n_scenes, self.n_actions, self.oracle.action_dim, generator=g)
        weights = torch.ones(self.n_scenes, self.n_actions)

        if self.boundary_focus > 0:
            actions, weights = self._boundary_resample(actions, g)

        self.actions = actions
        self.weights = weights / weights.sum()  # self-normalized over the whole dataset
        self.outcomes = self.oracle.query(self.states, self.actions)

    def _boundary_resample(
        self, actions: Tensor, g: torch.Generator
    ) -> tuple[Tensor, Tensor]:
        """Oversample actions near the outcome decision surface, and return the importance
        weights w = drho_target/drho_proposal that undo the bias.

        Proposal: with prob `boundary_focus`, replace an action by the most-boundary-like of
        `m` fresh draws (the one whose success probability is closest to 0.5). The resulting
        proposal density is not available in closed form, so we use the standard
        self-normalized surrogate: weight each retained action by 1 / (density surrogate),
        with the surrogate taken as the boundary-affinity that drove its selection. This is
        the estimator V4 debiases; the point of carrying it is that the bias is CORRECTED and
        MEASURABLE rather than hidden.
        """
        m = 8
        b, na, ad = actions.shape
        cand = torch.randn(b, na, m, ad, generator=g)
        with torch.no_grad():
            flat = cand.reshape(b, na * m, ad)
            p = torch.sigmoid(self.oracle.outcome_params(self.states, flat).reshape(b, na * m, 3)[..., 0])
        affinity = 1.0 - 2.0 * (p - 0.5).abs()  # 1 at the boundary, 0 at the extremes
        affinity = affinity.reshape(b, na, m)

        pick = affinity.argmax(dim=-1)  # (b, na)
        chosen = torch.gather(
            cand, 2, pick.view(b, na, 1, 1).expand(b, na, 1, ad)
        ).squeeze(2)
        chosen_aff = torch.gather(affinity, 2, pick.unsqueeze(-1)).squeeze(-1)

        use = torch.rand(b, na, generator=g) < self.boundary_focus
        actions = torch.where(use.unsqueeze(-1), chosen, actions)

        # w ∝ 1/proposal. Boundary-picked actions were oversampled by ~their affinity.
        w = torch.where(use, 1.0 / chosen_aff.clamp_min(0.05), torch.ones_like(chosen_aff))
        return actions, w

    def __len__(self) -> int:
        return self.n_scenes

    def __getitem__(self, i: int) -> dict[str, Tensor]:
        return {
            "observation": self.obs[i],
            "state": self.states[i],  # carried: J(x) needs it
            "actions": self.actions[i],
            "weights": self.weights[i],
            "succ": self.outcomes.succ[i],
            "margin": self.outcomes.margin[i],
            "slip": self.outcomes.slip[i],
        }


def collate(items: list[dict[str, Tensor]]) -> dict[str, Tensor]:
    out = {k: torch.stack([it[k] for it in items]) for k in items[0]}
    # Re-normalize the importance weights WITHIN the batch, since the loss reduces per batch.
    w = out["weights"]
    out["weights"] = w / w.sum().clamp_min(1e-12)
    return out
