"""Emit the main baseline table from results/rebuttal/*.json.

    python scripts/paper/make_baseline_table.py

Every cell is read from a result file; nothing is typed. The payload column is the
measured entropy-coded cost of shipping one scene's representation to the decision node,
which is what makes the comparison a network-edge comparison rather than an accuracy
leaderboard.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROWS = [
    ("MSP (ours)", "msp"),
    ("GQ-CNN architecture, retrained~\\cite{mahler2017}", "gqcnn"),
]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", default="results/rebuttal")
    ap.add_argument("--out", default="ICRA'27_MSP-FRAMEWORK/tab_baselines.tex")
    args = ap.parse_args()
    res = Path(args.results)

    r2 = {r["method"]: r for r in json.loads((res / "r2.json").read_text())}
    r5 = json.loads((res / "r5.json").read_text()) if (res / "r5.json").exists() else None
    r6 = json.loads((res / "r6.json").read_text()) if (res / "r6.json").exists() else None

    def payload(key: str, bits_per_dim: int) -> float:
        row = next(r for r in r6["sweep"] if r["bits_per_dim"] == bits_per_dim)
        return row[key]["payload_bits"]

    lines = []
    if r5:
        lines.append(("GQ-CNN architecture, retrained", r5, payload("gqcnn", 32) if r6 else None,
                      payload("gqcnn", 2) if r6 else None))
    lines.append(("MSP (ours)", r2["MSP (ours)"], payload("msp", 32) if r6 else None,
                  payload("msp", 2) if r6 else None))
    lines.append(("Direct success CNN, no bottleneck", r2["Direct success CNN (no bottleneck)"],
                  None, None))
    lines.append(("Ferrari--Canny on reconstructed box",
                  r2["Ferrari-Canny on reconstructed box"], None, None))
    lines.append(("Random", r2["Random"], None, None))

    def fmt(v):
        return "--" if v is None else (f"{v/8:.0f}" if v >= 8 else f"{v:.1f}")

    body = "\n".join(
        f"{name} & {r['pooled_auc']:.3f} & {r['within_scene_auc']:.3f} & "
        f"{r['top1_success']:.3f} & {fmt(fp32)} & {fmt(q2)} \\\\"
        for name, r, fp32, q2 in lines
    )
    tex = f"""% Generated by scripts/paper/make_baseline_table.py -- do not edit by hand.
\\begin{{table}}[t]
\\centering\\small
\\setlength{{\\tabcolsep}}{{4pt}}
\\caption{{Ranking quality and transport cost on the same candidate grasps. Payload is the
entropy-coded representation one scene must send to the decision node, in bytes; the
per-action column reflects that a grasp-aligned representation is formed after the action
is applied, so an edge deployment sends one per candidate. GQ-CNN ranks better when
bandwidth is unconstrained; MSP reaches its own operating point at two orders of magnitude
fewer bits, and is the stronger ranker at the tightest budget (Fig.~\\ref{{fig:frontier}}).}}
\\label{{tab:baselines}}
\\begin{{tabular}}{{lccccc}}
\\toprule
& \\multicolumn{{3}}{{c}}{{Ranking}} & \\multicolumn{{2}}{{c}}{{Payload (bytes)}} \\\\
\\cmidrule(lr){{2-4}}\\cmidrule(lr){{5-6}}
Method & Pooled AUC & Within-scene & Top-1 & fp32 & 2-bit \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(tex)
    print(tex)
    print("wrote", out)


if __name__ == "__main__":
    main()
