"""Turn results/*.json into LaTeX tables (booktabs) for the manuscript.

    python scripts/paper/make_tables.py --results results/ --out paper/tables/

Every number in every table comes from a JSON file produced by a run that actually happened.
Nothing is typed by hand into the .tex, which is the only way to guarantee the manuscript and
the experiments cannot drift apart.
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger("tables")

HEADER = (
    "%% AUTO-GENERATED by scripts/paper/make_tables.py -- DO NOT EDIT BY HAND.\n"
    "%% Regenerate with: python scripts/paper/make_tables.py\n"
    "%% Source: {src}\n"
)


def _load(results: Path, name: str):
    p = results / name
    if not p.exists():
        log.warning("SKIP %s (not found)", name)
        return None
    return json.loads(p.read_text())


def table_main(results: Path, out: Path) -> None:
    """Table 1: the headline result at the operating point."""
    rows = _load(results, "e3_coverage.json")
    if not rows:
        return
    r = min(rows, key=lambda x: abs(x["alpha"] - 0.1))  # the alpha = 0.1 operating point

    tex = HEADER.format(src="e3_coverage.json") + rf"""
\begin{{table}}[t]
\centering
\caption{{Calibrated abstention at the $\alpha=0.1$ operating point. Coverage is the
\emph{{marginal}} quantity of Theorem~\ref{{thm:coverage}}, $\Pr(\mathrm{{succ}} \in C(o,a))$,
measured over all test points. Certified precision, $\Pr(\mathrm{{succ}}=1 \mid a \in
\mathcal{{A}}_{{\mathrm{{cert}}}})$, is a different estimand and is reported separately.}}
\label{{tab:main}}
\begin{{tabular}}{{lr}}
\toprule
Quantity & Value \\
\midrule
Target coverage $1-\alpha$          & {r['target_coverage']:.2f} \\
Empirical coverage (Thm.~7)         & \textbf{{{r['coverage']:.3f}}} \\
Certified precision                 & {r['certified_precision']:.3f} \\
Abstention rate                     & {r['abstention_rate']:.3f} \\
Certified action fraction           & {r['certified_fraction']:.3f} \\
Mean ambiguity $\mathbb{{E}}[U(o)]$   & {r['mean_ambiguity']:.4f} \\
\midrule
Rate $R$ [nats]                     & {r['rate']:.3f} \\
Outcome distortion $D$ [nats]       & {r['distortion']:.4f} \\
Test points                         & {r['n_points']:,} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_main.tex").write_text(tex)
    log.info("wrote tab_main.tex")


def table_identifiability(results: Path, out: Path) -> None:
    """Table 2: contribution C2. The identifiability result, with ground truth."""
    r = _load(results, "e2_identifiability.json")
    if not r:
        return
    tex = HEADER.format(src="e2_identifiability.json") + rf"""
\begin{{table}}[t]
\centering
\caption{{Identifiability (Theorem~\ref{{thm:identifiability}}). The predicted
$\ker J(x)$ is compared against a subspace measured \emph{{independently}}, by perturbing the
state and recording which directions leave real outcomes unchanged. Principal angles near
zero mean the two subspaces coincide: the unidentifiable directions predicted by the theory
are exactly the ones that manipulation cannot distinguish.}}
\label{{tab:identifiability}}
\begin{{tabular}}{{lrr}}
\toprule
& Ground truth & Estimated \\
\midrule
State dimension $d_X$          & {r['state_dim']}      & --- \\
$\mathrm{{rank}}\,J(x)$          & {r['true_rank']}      & {r['estimated_rank_mean']:.2f} \\
$\dim \ker J(x)$               & {r['true_null_dim']}  & {r['estimated_null_dim_mean']:.2f} \\
\midrule
\multicolumn{{3}}{{l}}{{\emph{{Principal angles, predicted vs.\ measured invariant subspace}}}} \\
Mean [deg]                     & \multicolumn{{2}}{{r}}{{{r['mean_angle_deg']:.3f}}} \\
Max [deg]                      & \multicolumn{{2}}{{r}}{{{r['max_angle_deg']:.3f}}} \\
States evaluated               & \multicolumn{{2}}{{r}}{{{r['n_states']}}} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_identifiability.tex").write_text(tex)
    log.info("wrote tab_identifiability.tex")


def table_ablations(results: Path, out: Path) -> None:
    """Table 3: the controls. z-ablation (attack 21) and the value of abstention."""
    rows = _load(results, "e4_ablations.json")
    if not rows:
        return
    by = {r.get("ablation"): r for r in rows}
    full, zab, abst = by.get("full"), by.get("z_ablated"), by.get("abstention_effect")
    if not (full and zab and abst):
        log.warning("e4 incomplete; skipping tab_ablations")
        return

    delta = zab["distortion"] - full["distortion"]

    tex = HEADER.format(src="e4_ablations.json") + rf"""
\begin{{table}}[t]
\centering
\caption{{Ablations. \emph{{$z$-ablation}} replaces the belief with a constant, so the outcome
head can only exploit an action prior; the distortion must rise, or the sufficient statistic
is not being used (reviewer concern: ``the head could ignore $z$ and memorise action
priors''). \emph{{Abstention}} compares acting only on certified actions against always acting.}}
\label{{tab:ablations}}
\begin{{tabular}}{{lrr}}
\toprule
Variant & Distortion $D$ & Coverage \\
\midrule
Full model            & \textbf{{{full['distortion']:.4f}}} & {full['coverage']:.3f} \\
$z$-ablated           & {zab['distortion']:.4f} & {zab['coverage']:.3f} \\
\quad $\Delta$        & \textbf{{$+{delta:.4f}$}} & --- \\
\bottomrule
\end{{tabular}}

\vspace{{0.6em}}

\begin{{tabular}}{{lrr}}
\toprule
Policy & Success when acting & Episodes acted \\
\midrule
With abstention (Eq.~24)  & \textbf{{{abst['with_abstention_success']:.3f}}} & {abst['with_abstention_acted']} / {abst['n_episodes']} \\
Always act (no certificate) & {abst['no_abstention_success']:.3f} & {abst['n_episodes']} / {abst['n_episodes']} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_ablations.tex").write_text(tex)
    log.info("wrote tab_ablations.tex")


def table_frontier(results: Path, out: Path) -> None:
    rows = _load(results, "e1_frontier.json")
    if not rows:
        return
    rows = sorted(rows, key=lambda r: r["beta"])
    body = "\n".join(
        rf"{r['beta']:g} & {r['rate']:.3f} & {r['distortion']:.4f} & {r['coverage']:.3f} \\"
        for r in rows
    )
    tex = HEADER.format(src="e1_frontier.json") + rf"""
\begin{{table}}[t]
\centering
\caption{{Rate--distortion frontier over the sufficiency budget $\beta$. $\beta$ multiplies
the relevance term (Eq.~7), so larger $\beta$ purchases sufficiency at the price of rate,
and $\beta\to\infty$ recovers sufficiency (Theorem~\ref{{thm:ib}}).}}
\label{{tab:frontier}}
\begin{{tabular}}{{rrrr}}
\toprule
$\beta$ & Rate $R$ & Distortion $D$ & Coverage \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_frontier.tex").write_text(tex)
    log.info("wrote tab_frontier.tex")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", type=Path, default=Path("results"))
    ap.add_argument("--out", type=Path, default=Path("paper/tables"))
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    table_main(args.results, args.out)
    table_identifiability(args.results, args.out)
    table_ablations(args.results, args.out)
    table_frontier(args.results, args.out)
    log.info("tables -> %s", args.out)


if __name__ == "__main__":
    main()
