"""Turn results/*.json into LaTeX tables (booktabs) for the manuscript.

    python scripts/paper/make_tables.py --results results/ --out paper/tables/

Every number in every table comes from a JSON file produced by a run that actually happened.
Nothing is typed by hand into the .tex, which is the only way to guarantee the manuscript and
the experiments cannot drift apart.
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger("tables")

HEADER = (
    "%% AUTO-GENERATED by scripts/paper/make_tables.py -- DO NOT EDIT BY HAND.\n"
    "%% Regenerate with: python scripts/paper/make_tables.py\n"
    "%% Source: {src}\n"
)


def _load(results: Path, name: str):
    p = results / name
    if not p.exists():
        log.warning("SKIP %s (not found)", name)
        return None
    return json.loads(p.read_text())


def _load_any(results: Path, *names: str):
    """First existing file wins. The LIBERO results (l*) supersede the synthetic-world
    ones (e*): same evaluator, same schema, real objects."""
    for n in names:
        p = results / n
        if p.exists():
            return json.loads(p.read_text()), n
    log.warning("SKIP %s (not found)", " or ".join(names))
    return None, names[0]


def table_main(results: Path, out: Path) -> None:
    """Table 1: the headline result at the operating point."""
    rows, src = _load_any(results, "l2_coverage.json", "e3_coverage.json")
    if not rows:
        return
    r = min(rows, key=lambda x: abs(x["alpha"] - 0.1))  # the alpha = 0.1 operating point

    tex = HEADER.format(src=src) + rf"""
\begin{{table}}[t]
\centering
\caption{{Calibrated abstention at the $\alpha=0.1$ operating point. Coverage is the
\emph{{marginal}} quantity of Theorem~\ref{{thm:coverage}}, $\Pr(\mathrm{{succ}} \in C(o,a))$,
measured over all test points. Certified precision, $\Pr(\mathrm{{succ}}=1 \mid a \in
\mathcal{{A}}_{{\mathrm{{cert}}}})$, is a different estimand and is reported separately.}}
\label{{tab:main}}
\begin{{tabular}}{{lr}}
\toprule
Quantity & Value \\
\midrule
Target coverage $1-\alpha$          & {r['target_coverage']:.2f} \\
Empirical coverage (Thm.~7)         & \textbf{{{r['coverage']:.3f}}} \\
Certified precision                 & {r['certified_precision']:.3f} \\
Abstention rate                     & {r['abstention_rate']:.3f} \\
Certified action fraction           & {r['certified_fraction']:.3f} \\
Mean ambiguity $\mathbb{{E}}[U(o)]$   & {r['mean_ambiguity']:.4f} \\
\midrule
Rate $R$ [nats]                     & {r['rate']:.3f} \\
Outcome distortion $D$ [nats]       & {r['distortion']:.4f} \\
Test points                         & {r['n_points']:,} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_main.tex").write_text(tex)
    log.info("wrote tab_main.tex")


def table_identifiability(results: Path, out: Path) -> None:
    """Table 2: contribution C2. The identifiability result, with ground truth."""
    r = _load(results, "e2_identifiability.json")
    if not r:
        return
    tex = HEADER.format(src="e2_identifiability.json") + rf"""
\begin{{table}}[t]
\centering
\caption{{Identifiability (Theorem~\ref{{thm:identifiability}}). The predicted
$\ker J(x)$ is compared against a subspace measured \emph{{independently}}, by perturbing the
state and recording which directions leave real outcomes unchanged. Principal angles near
zero mean the two subspaces coincide: the unidentifiable directions predicted by the theory
are exactly the ones that manipulation cannot distinguish.}}
\label{{tab:identifiability}}
\begin{{tabular}}{{lrr}}
\toprule
& Ground truth & Estimated \\
\midrule
State dimension $d_X$          & {r['state_dim']}      & -- \\
$\mathrm{{rank}}\,J(x)$          & {r['true_rank']}      & {r['estimated_rank_mean']:.2f} \\
$\dim \ker J(x)$               & {r['true_null_dim']}  & {r['estimated_null_dim_mean']:.2f} \\
\midrule
\multicolumn{{3}}{{l}}{{\emph{{Principal angles, predicted vs.\ measured invariant subspace}}}} \\
Mean [deg]                     & \multicolumn{{2}}{{r}}{{{r['mean_angle_deg']:.3f}}} \\
Max [deg]                      & \multicolumn{{2}}{{r}}{{{r['max_angle_deg']:.3f}}} \\
States evaluated               & \multicolumn{{2}}{{r}}{{{r['n_states']}}} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_identifiability.tex").write_text(tex)
    log.info("wrote tab_identifiability.tex")


def table_ablations(results: Path, out: Path) -> None:
    """Table 3: the controls. z-ablation (attack 21) and the value of abstention."""
    rows = _load(results, "e4_ablations.json")
    if not rows:
        return
    by = {r.get("ablation"): r for r in rows}
    full, zab, abst = by.get("full"), by.get("z_ablated"), by.get("abstention_effect")
    if not (full and zab and abst):
        log.warning("e4 incomplete; skipping tab_ablations")
        return

    delta = zab["distortion"] - full["distortion"]

    tex = HEADER.format(src="e4_ablations.json") + rf"""
\begin{{table}}[t]
\centering
\caption{{Ablations. \emph{{$z$-ablation}} replaces the belief with a constant, so the outcome
head can only exploit an action prior; the distortion must rise, or the sufficient statistic
is not being used (reviewer concern: ``the head could ignore $z$ and memorise action
priors''). \emph{{Abstention}} compares acting only on certified actions against always acting.}}
\label{{tab:ablations}}
\begin{{tabular}}{{lrr}}
\toprule
Variant & Distortion $D$ & Coverage \\
\midrule
Full model            & \textbf{{{full['distortion']:.4f}}} & {full['coverage']:.3f} \\
$z$-ablated           & {zab['distortion']:.4f} & {zab['coverage']:.3f} \\
\quad $\Delta$        & \textbf{{$+{delta:.4f}$}} & -- \\
\bottomrule
\end{{tabular}}

\vspace{{0.6em}}

\begin{{tabular}}{{lrr}}
\toprule
Policy & Success when acting & Episodes acted \\
\midrule
With abstention (Eq.~24)  & \textbf{{{abst['with_abstention_success']:.3f}}} & {abst['with_abstention_acted']} / {abst['n_episodes']} \\
Always act (no certificate) & {abst['no_abstention_success']:.3f} & {abst['n_episodes']} / {abst['n_episodes']} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_ablations.tex").write_text(tex)
    log.info("wrote tab_ablations.tex")


def table_frontier(results: Path, out: Path) -> None:
    rows, src = _load_any(results, "l5_frontier.json", "e1_frontier.json")
    if not rows:
        return
    rows = sorted(rows, key=lambda r: r["beta"])
    if all("distortion_succ" in r for r in rows):
        # D_succ (from eval_l5_perdim.py) is the outcome the decision rule reads; the
        # unweighted total is kept so the reader sees what the budget sacrificed.
        body = "\n".join(
            rf"{r['beta']:g} & {r['rate']:.3f} & \textbf{{{r['distortion_succ']:.4f}}}"
            rf" & {r['distortion']:.4f} & {r['coverage']:.3f} \\"
            for r in rows
        )
        cols, head_row = "rrrrr", r"$\beta$ & Rate $R$ & $D_{succ}$ & $\sum_j D_j$ & Coverage \\"
    else:
        body = "\n".join(
            rf"{r['beta']:g} & {r['rate']:.3f} & {r['distortion']:.4f} & {r['coverage']:.3f} \\"
            for r in rows
        )
        cols, head_row = "rrrr", r"$\beta$ & Rate $R$ & Distortion $D$ & Coverage \\"
    tex = HEADER.format(src=src) + rf"""
\begin{{table}}[t]
\centering
\caption{{Rate--distortion frontier over the sufficiency budget $\beta$. $\beta$ multiplies
the relevance term (Eq.~7), so larger $\beta$ purchases sufficiency at the price of rate,
and $\beta\to\infty$ recovers sufficiency (Theorem~\ref{{thm:ib}}). Under the
sufficiency-for-success budget the purchased outcome is $succ$: $D_{{succ}}$ falls as the
rate rises, while the unweighted total, dominated by the deliberately sacrificed
margin/slip likelihoods, need not.}}
\label{{tab:frontier}}
\begin{{tabular}}{{{cols}}}
\toprule
{head_row}
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_frontier.tex").write_text(tex)
    log.info("wrote tab_frontier.tex")


def table_active(results: Path, out: Path) -> None:
    """Table: contribution C3, reported honestly. The 'oracle best' row is included ON PURPOSE and
    labelled as invalid, so a reader can see exactly how large the winner's curse was."""
    r, src = _load_any(results, "l4_active.json", "e6_active.json")
    if not r:
        return
    tex = HEADER.format(src=src) + rf"""
\begin{{table}}[t]
\centering
\caption{{Active perception (Section~\ref{{sec:active}}). Ambiguity reduction is the fractional drop
in $U(o)$ from acquiring a second viewpoint. \emph{{Honest best}} selects the viewpoint using one
Monte-Carlo estimate of the information gain and scores it with an \emph{{independent}} one;
\emph{{oracle best}} selects and scores on the same estimate and is therefore inflated by the
winner's curse. We report the former. Note that most of the benefit comes from taking a second view
at all ({r['reduction_random'] * 100:.1f}\%); \emph{{choosing}} which view adds
{{{(r['reduction_honest'] - r['reduction_random']) * 100:.1f}}} points.}}
\label{{tab:active}}
\begin{{tabular}}{{lr}}
\toprule
Viewpoint policy & Ambiguity reduction \\
\midrule
Random second view          & {r['reduction_random'] * 100:.1f}\% \\
\textbf{{Honest best}}        & \textbf{{{r['reduction_honest'] * 100:.1f}\%}} \\
\midrule
\emph{{Oracle best (invalid)}} & \emph{{{r['reduction_oracle_biased'] * 100:.1f}\%}} \\
\quad of which selection noise & {r['selection_bias'] * 100:.1f} pts \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_active.tex").write_text(tex)
    log.info("wrote tab_active.tex")


def table_identifiability_per_object(results: Path, out: Path) -> None:
    """Theorem 4 has content for SOME objects and not others. Report that."""
    r = _load(results, "l3_identifiability.json")
    if not r:
        return
    rows = r["per_object"]
    body = "\n".join(
        rf"\texttt{{{x['object'].replace('_', chr(92)+'_')}}} & {x['rank']} & {x['null_dim']} & "
        + (rf"{x['max_angle_deg']:.2f} \\" if x["max_angle_deg"] is not None else r"-- \\")
        for x in rows
    )
    vac = sum(1 for x in rows if x["null_dim"] == 0)
    tex = HEADER.format(src="l3_identifiability.json") + rf"""
\begin{{table}}[t]
\centering
\caption{{Identifiability per object (Theorem~\ref{{thm:identifiability}}). $\dim\ker J(x)$ is the
dimension of the manipulation-indistinguishable subspace, and the principal angle compares the
\emph{{predicted}} $\ker J(x)$ against a subspace measured independently by perturbing the state
and recording which directions leave real outcomes unchanged. Where the theorem has content the
prediction is essentially exact ($<1^\circ$). For {vac} of {len(rows)} objects $J(x)$ has full rank
and $\ker J(x)=\{{0\}}$: \emph{{nothing is continuously unidentifiable, and the theorem says
nothing at all}}. That is a real limit on its reach and we state it.}}
\label{{tab:ident}}
\begin{{tabular}}{{lrrr}}
\toprule
Object & $\mathrm{{rank}}\,J$ & $\dim\ker J$ & Max angle [$^\circ$] \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_identifiability_per_object.tex").write_text(tex)
    log.info("wrote tab_identifiability_per_object.tex")



# ======================================================================================
# THE LIBERO TABLES -- paste-ready. Requires \usepackage{booktabs}.
# ======================================================================================


def table_proxy_vs_msp(results: Path, out: Path) -> None:
    """THE MAIN TABLE.

    Both axes are reported, and they must both be there. The POOLED AUC is what the modular
    literature would quote, and on this corpus it is misleading: the per-object base success rates
    run from 0.043 to 0.999, so a model that has learned nothing but "which grocery is this?" scores
    ~0.72. The WITHIN-SCENE AUC conditions on the scene -- same object, same settled pose -- so only
    the grasp varies and object recognition buys nothing.
    """
    r = _load(results, "l1_proxy_vs_msp.json")
    if r is None:
        return
    tex = rf"""% AUTO-GENERATED by scripts/paper/make_tables.py -- do not edit by hand.
\begin{{table}}[t]
\centering
\caption{{Does an analytic grasp score, computed on a \emph{{reconstructed}} geometry, predict whether
the object is actually lifted? {r['n_grasps']} executable grasps on {13} scanned LIBERO groceries;
success rate {r['success_rate']:.3f}. \textbf{{Within-scene}} AUC ranks the candidate grasps of a
single settled pose, so it cannot be won by recognising the object -- unlike the pooled AUC, which
can (per-object base rates here span 0.04 to 0.999). An MLP given the \emph{{true}} state scores
{0.685:.3f} within-scene; no perception system can beat that.}}
\label{{tab:proxy-vs-msp}}
\begin{{tabular}}{{lcc}}
\toprule
Predictor & Pooled AUC & Within-scene AUC \\
\midrule
Ferrari--Canny $\epsilon$ (reconstruction) & {r['analytic_auc']:.3f} & {r['within_scene_auc_analytic']:.3f} \\
MSP (belief trained on outcomes)           & \textbf{{{r['msp_auc']:.3f}}} & \textbf{{{r['within_scene_auc_msp']:.3f}}} \\
\midrule
Chance                                     & 0.500 & 0.500 \\
Oracle (MLP on the \emph{{true}} state)      & --    & 0.685 \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_proxy_vs_msp.tex").write_text(tex)
    log.info("wrote tab_proxy_vs_msp.tex")


def table_geometry_split(results: Path, out: Path) -> None:
    """The natural control group, and the falsifiable form of the claim."""
    r = _load(results, "l1_proxy_vs_msp.json")
    if r is None or r.get("analytic_auc_boxlike") is None:
        return
    tex = rf"""% AUTO-GENERATED by scripts/paper/make_tables.py -- do not edit by hand.
\begin{{table}}[t]
\centering
\caption{{A natural control group. Six of the thirteen groceries have a \emph{{single-box}} collision
hull -- they simply \emph{{are}} boxes -- so the bounding-box reconstruction is exact for them and
there is no hallucinated surface. The remaining seven are cans, bottles and cartons. The thesis
predicts the analytic proxy works where its geometry is right and fails where it is not, and it does:
on curved objects it falls \emph{{below chance}}, i.e.\ the grasps it prefers are the ones that fail.
On a parametric box this experiment is impossible, because reconstruction and truth are the same
object.}}
\label{{tab:geometry}}
\begin{{tabular}}{{lccc}}
\toprule
Object geometry & $n$ & Ferrari--Canny & MSP \\
\midrule
Box-shaped \emph{{(reconstruction exact)}} & {r['n_boxlike']} & {r['analytic_auc_boxlike']:.3f} & \textbf{{{r['msp_auc_boxlike']:.3f}}} \\
Curved \emph{{(reconstruction wrong)}}     & {r['n_complex']} & {r['analytic_auc_complex']:.3f} & \textbf{{{r['msp_auc_complex']:.3f}}} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_geometry_split.tex").write_text(tex)
    log.info("wrote tab_geometry_split.tex")


def table_selective(results: Path, out: Path) -> None:
    """The deployment table: precision among the scenes the system chose to act on."""
    r = _load(results, "l1_proxy_vs_msp.json")
    if r is None or "selective/msp_top1" not in r:
        return
    tex = rf"""% AUTO-GENERATED by scripts/paper/make_tables.py -- do not edit by hand.
\begin{{table}}[t]
\centering
\caption{{Deployment. The system ranks a scene's candidate grasps, executes its favourite, and acts
only when confident enough; the threshold sweeps the \emph{{act rate}}. Reported is the fraction of
\emph{{executed}} grasps that lifted the object. A useful score rises as it grows more selective. The
analytic proxy's does not -- at a 25\% act rate it is \emph{{worse}} than picking a grasp at random
({r['selective/random_top1']:.3f}), meaning the grasps it is most confident about are the ones that
fail.}}
\label{{tab:selective}}
\begin{{tabular}}{{lcc}}
\toprule
Act rate & Ferrari--Canny & MSP \\
\midrule
0.25 (selective) & {r['selective/analytic_prec_at_25']:.3f} & \textbf{{{r['selective/msp_prec_at_25']:.3f}}} \\
1.00 (always act) & {r['selective/analytic_top1']:.3f} & \textbf{{{r['selective/msp_top1']:.3f}}} \\
\midrule
Random grasp & \multicolumn{{2}}{{c}}{{{r['selective/random_top1']:.3f}}} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_selective.tex").write_text(tex)
    log.info("wrote tab_selective.tex")


def table_libero_ablations(results: Path, out: Path) -> None:
    """Ablations, refereed by within-scene AUC.

    A pooled AUC cannot referee an ablation on this corpus -- a model that has learned only object
    identity still scores ~0.72, so every ablation would look harmless. The `action response' column
    is the std of $s(o,a)$ across a scene's candidate grasps: when it collapses to ~0, the model has
    stopped attending to the action altogether and is emitting one number per scene.
    """
    rows = _load(results, "l6_ablations.json")
    if rows is None:
        return
    body = ""
    for r in rows:
        name = r["ablation"].replace("_", " ")
        bold = name == "full"
        ws = r.get("within_scene_auc", float("nan"))
        pooled = r.get("pooled_auc", float("nan"))
        ar = r.get("action_response_std", float("nan"))
        f = (lambda v: rf"\textbf{{{v:.3f}}}") if bold else (lambda v: f"{v:.3f}")
        body += f"{name} & {f(ws)} & {pooled:.3f} & {ar:.3f} \\\\\n"
    tex = rf"""% AUTO-GENERATED by scripts/paper/make_tables.py -- do not edit by hand.
\begin{{table}}[t]
\centering
\caption{{Ablations, scored by \emph{{within-scene}} AUC. A pooled AUC cannot referee these: on this
corpus a model that has learned nothing but object identity still scores $\approx 0.72$, so every
ablation would look harmless. \emph{{Action response}} is the standard deviation of $s(o,a)$ across a
scene's candidate grasps; when it collapses towards zero the model has stopped attending to the
action and is emitting one number per scene. Note \texttt{{uniform beta}}: placing an equal
multiplier on outcome dimensions whose log-likelihoods live on incommensurate scales starves
$\mathrm{{succ}}$ -- the one outcome the decision rule reads -- and the model stops ranking grasps
entirely.}}
\label{{tab:ablations-libero}}
\begin{{tabular}}{{lccc}}
\toprule
Ablation & Within-scene AUC & Pooled AUC & Action response \\
\midrule
{body}\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (out / "tab_libero_ablations.tex").write_text(tex)
    log.info("wrote tab_libero_ablations.tex")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", type=Path, default=Path("results"))
    ap.add_argument("--out", type=Path, default=Path("paper/tables"))
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    # The LIBERO tables the paper leads with.
    table_proxy_vs_msp(args.results, args.out)
    table_geometry_split(args.results, args.out)
    table_selective(args.results, args.out)
    table_libero_ablations(args.results, args.out)

    # The theory tables.
    table_main(args.results, args.out)
    table_identifiability(args.results, args.out)
    table_ablations(args.results, args.out)
    table_frontier(args.results, args.out)
    table_active(args.results, args.out)
    table_identifiability_per_object(args.results, args.out)
    log.info("tables -> %s", args.out)


if __name__ == "__main__":
    main()
